### PR TITLE
Creating a patch for Honkai Impact 3rd

### PR DESCRIPTION
**Pull request by Rathmox**
I currently using your work on Genshin Impact to use it for Honkai Impact 3rd, but I still have some issues and I may need help

### CODE REVIEW

**Comment by Rathmox** [comment]
Currently it works only for Europe and America version (problem with folder naming)

**Comment by Rathmox** [comment]
My main problem here is that the game takes all the RAM and CPU and gets killed by the kernel, so I can't run the game for now

**Comment by legluondunet** [comment]
Hello @Rathmox , could you tell me why did you close this pull request?

**Comment by Rathmox** [comment]
I'm trying to create a patch for Honkai Impact based on your work for Genshin, but it's starting to get really different than the Genshin patch so I prefer creating a repo myself

**Comment by legluondunet** [comment]
Ok, nice work.

**Pull request closed without merging**
