### PR TITLE
feat: add Genshin Impact 2.8.0 patch

### PR DESCRIPTION
**Pull request by zeroday0619**
I haven't tested it yet.

### CODE REVIEW

**Comment by zeroday0619** [comment]
do not merge yet

**Comment by jmyrick02** [comment]
It works, thank you!

**Comment by legluondunet** [comment]
Hello @zeroday0619 , nice work. But for the moment there is not a stable version of the patch. I prefer waiting for the stable version. 
Could you tell me why you modified script like this:
./xterm --> xterm?

**Comment by legluondunet** [comment]
I close this pull request as I prefer to not distribute unstable patch version.

**Pull request closed without merging**
